### ISSUE TITLE
no GUI launch, Snapd

### ISSUE THREAD

**Issue by tidypy** [Lin-Buo-Ren/waifu2x-ncnn-vulkan-snap#4]
Linux Mint 20, installed through Snapd  ;  

Does nothing after running the command:  
@LinuxMint20:~$ waifu2x-ncnn-vulkan 
Usage: waifu2x [image] [outputpng] [noise=-1/0/1/2/3] [scale=1/2] [tilesize=400]

**Comment by brlin-tw** [comment]
This is not a GUI application, please use it in a terminal.
